/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BodyCard: typeof import('./client/components/BodyCard.vue')['default']
    BodyCardModal: typeof import('./client/components/BodyCardModal.vue')['default']
    ConfirmPopup: typeof import('primevue/confirmpopup')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    FooterCard: typeof import('./client/components/FooterCard.vue')['default']
    HeaderCard: typeof import('./client/components/HeaderCard.vue')['default']
    RowModal: typeof import('./client/components/RowModal.vue')['default']
    RowPanel: typeof import('./client/components/RowPanel.vue')['default']
  }
}
